### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by TcM1911** [goretk/gore#21]
Support for processing ARM binaries.

**Comment by 0xdevalias** [comment]
I believe the below is related to this issue (adding here particularly for context of error messages/etc since this issue didn't show up when I searched originally):

---

> ```
> $ /opt/homebrew/Cellar/redress/1.1.1/bin/redress info /opt/homebrew/Cellar/redress/1.1.1/bin/redress
> panic: Unsupported architecture
> 
> goroutine 1 [running]:
> github.com/goretk/gore.(*machoFile).getFileInfo(0x1400002c4a0)
> 	github.com/goretk/gore@v0.11.1/macho.go:117 +0xdc
> github.com/goretk/gore.Open({0x16f1e6a84, 0x2e})
> 	github.com/goretk/gore@v0.11.1/file.go:86 +0x348
> main.listInfo({0x16f1e6a84?, 0x0?})
> 	github.com/goretk/redress/info.go:50 +0x90
> main.init.1.func1(0x140000e6e00?, {0x1400002c300?, 0x4?, 0x100e4f6df?})
> 	github.com/goretk/redress/info.go:25 +0x30
> github.com/spf13/cobra.(*Command).execute(0x140000c4280, {0x1400002c2e0, 0x1, 0x1})
> 	github.com/spf13/cobra@v1.2.1/command.go:860 +0x53c
> github.com/spf13/cobra.(*Command).ExecuteC(0x1010dd2c0)
> 	github.com/spf13/cobra@v1.2.1/command.go:974 +0x318
> github.com/spf13/cobra.(*Command).Execute(...)
> 	github.com/spf13/cobra@v1.2.1/command.go:902
> main.main()
> 	github.com/goretk/redress/main.go:25 +0x24
> ```
> 
> is this only for x86?
> 
> _Originally posted by @chenrui333 in https://github.com/Homebrew/homebrew-core/pull/155724#discussion_r1407055279_

---

> That seems to be coming from the `gore` lib that `redress` depends on:
> 
> https://github.com/goretk/gore/blob/78568206ae24043a24fc8bf89443ad6164a7509f/macho.go#L104-L123
> 
> ---
> 
> What system were you trying to run it on?
> 
> _Originally posted by @0xdevalias in https://github.com/Homebrew/homebrew-core/pull/155724#discussion_r1407056976_

---

> I am trying on ventura arm, if does not run for arm, then we probably need `depends_on arch: :x86_64` as well as some upstream note on it
> 
> _Originally posted by @chenrui333 in https://github.com/Homebrew/homebrew-core/pull/155724#discussion_r1407058050_

**Comment by 0xdevalias** [comment]
@TcM1911 I believe this may have been fixed by @derekparker in:

- https://github.com/goretk/gore/pull/72
